const categoryData = [
  { id: 0, title: "Random" },
  { id: 9, title: "General Knowledge" },
  { id: 10, title: "Books" },
  { id: 11, title: "Film" },
  { id: 12, title: "Music" },
  { id: 13, title: "Musicals & Theatres" },
  { id: 14, title: "Television" },
  { id: 15, title: "Video Games" },
  { id: 16, title: "Board Games" },
  { id: 17, title: "Science & Nature" },
  { id: 18, title: "Computers" },
  { id: 19, title: "Mathematics" },
  { id: 20, title: "Mythology" },
  { id: 21, title: "Sports" },
  { id: 22, title: "Geography" },
  { id: 23, title: "History" },
  { id: 24, title: "Politics" },
  { id: 25, title: "Art" },
  { id: 26, title: "Celebrities" },
  { id: 27, title: "Animals" },
  { id: 28, title: "Vehicles" },
  { id: 29, title: "Comics" },
  { id: 30, title: "Gadgets" },
  { id: 31, title: "Anime" },
  { id: 32, title: "Cartoons" },
];

export default categoryData;
